### ISSUE TITLE
mkvirtualenv+pip install: have you tried to do it?

### ISSUE THREAD

**Issue by kai3341** [Javinator9889/py-GSearch-API#1]
```
kai@ASCUE68-42:~$ workon gs
(gs) kai@ASCUE68-42:~$ pip freeze
py-GSearch-API==1.34
readline==6.2.4.1
(gs) kai@ASCUE68-42:~$ pip show py-GSearch-API
Name: py-GSearch-API
Version: 1.34
Summary: A simple Python API for searching web with Google
Home-page: https://github.com/Javinator9889/py-GSearch-API
Author: Javinator9889
Author-email: javialonso007@hotmail.es
License: GNU General Public License v3.0
Location: /home/kai/.virtualenvs/gs/lib/python3.4/site-packages
Requires: 
Required-by: 
(gs) kai@ASCUE68-42:~$ ls /home/kai/.virtualenvs/gs/lib/python3.4/site-packages
easy_install.py  pip-18.1.dist-info  py_GSearch_API-1.34.dist-info  setuptools			 wheel-0.32.2.dist-info
gsearch		 pkg_resources	     readline-6.2.4.1.dist-info     setuptools-40.6.2.dist-info
pip		 __pycache__	     readline.cpython-34m.so	    wheel
(gs) kai@ASCUE68-42:~$ python
Python 3.4.2 (default, Sep 25 2018, 22:02:39) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gsearch
Traceback (most recent call last):
  File "/home/kai/.virtualenvs/gs/lib/python3.4/site-packages/gsearch/gsearch.py", line 2, in <module>
    import requests as rq
ImportError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kai/.virtualenvs/gs/lib/python3.4/site-packages/gsearch/__init__.py", line 1, in <module>
    from gsearch.gsearch import search
  File "/home/kai/.virtualenvs/gs/lib/python3.4/site-packages/gsearch/gsearch.py", line 3, in <module>
    except (ImportError, ModuleNotFoundError):
NameError: name 'ModuleNotFoundError' is not defined
>>> 
(gs) kai@ASCUE68-42:~$ pip install requests
Collecting requests
  Downloading https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 133kB/s 
Collecting urllib3<1.25,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 142kB/s 
Collecting certifi>=2017.4.17 (from requests)
  Downloading https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl (146kB)
    100% |████████████████████████████████| 153kB 150kB/s 
Collecting idna<2.8,>=2.5 (from requests)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 139kB/s 
Installing collected packages: urllib3, chardet, certifi, idna, requests
Successfully installed certifi-2018.10.15 chardet-3.0.4 idna-2.7 requests-2.20.1 urllib3-1.24.1
(gs) kai@ASCUE68-42:~$ pip install gsearch
Collecting gsearch
  Downloading https://files.pythonhosted.org/packages/26/d2/65a84b0b4f9bc7136551f24ed08628eb2aea1f713a7d4642500fe55d128d/gsearch-1.6.0-py2.py3-none-any.whl
^COperation cancelled by user
(gs) kai@ASCUE68-42:~$ ^C
(gs) kai@ASCUE68-42:~$ ^C
(gs) kai@ASCUE68-42:~$ python
Python 3.4.2 (default, Sep 25 2018, 22:02:39) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gsearch
Traceback (most recent call last):
  File "/home/kai/.virtualenvs/gs/lib/python3.4/site-packages/gsearch/gsearch.py", line 8, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kai/.virtualenvs/gs/lib/python3.4/site-packages/gsearch/__init__.py", line 1, in <module>
    from gsearch.gsearch import search
  File "/home/kai/.virtualenvs/gs/lib/python3.4/site-packages/gsearch/gsearch.py", line 9, in <module>
    except (ImportError, ModuleNotFoundError):
NameError: name 'ModuleNotFoundError' is not defined
>>> 
(gs) kai@ASCUE68-42:~/.virtualenvs/gs/lib/python3.4/site-packages/gsearch$ grep -hER 'import|from' | awk {'printf $2"\n"'} | grep -Ev 'gsearch|re|json' | sort -u | xargs pip install
```
do you know, why and how `Exception`s works?
Thank you for really good example, how i mustn't to create API
```
>>> r = gsearch.gsearch.search(query='hello, world!', lang='en/us', num=50)
One or more args were not given. Check and then, retry the searching
```
fine. rmvirtualenv

**Comment by Javinator9889** [comment]
@kai3341 Hi, this library is no longer updated. Please, I recommend you to move to pyGle (https://github.com/Javinator9889/pyGle).

I will revise your issue if you are interested in, but I encourage you to move to pyGle ^^
